insert into astrologies(name, img_url, description) values ("Sagittarius","/Horoscope/react-front-end/public/sagittarius.jpeg","this is Sagittarius description!!");
insert into astrologies(name, img_url, description) values ("Capricorn","/Horoscope/react-front-end/public/capricorn.jpeg","this is Capricorn description!!");
insert into astrologies(name, img_url, description) values ("Aquarius","/Horoscope/react-front-end/public/aquarius.jpeg","this is Aquarius description!!");
insert into astrologies(name, img_url, description) values ("Pisces", "/Horoscope/react-front-end/public/pisces.jpeg", "this is Pisces description!!");
insert into astrologies(name, img_url, description) values ("Aries","/Horoscope/react-front-end/public/aquarius.jpeg","this is Aries description!!");
insert into astrologies(name, img_url, description) values ("Taurus","/Horoscope/react-front-end/public/aries.jpeg","this is Taurus description!!");
insert into astrologies(name, img_url, description) values ("Gemini","/Horoscope/react-front-end/public/gemini.jpeg","this is Gemini description!!");
insert into astrologies(name, img_url, description) values ("Cancer","/Horoscope/react-front-end/public/cancer.jpeg","this is Cancer description!!");
insert into astrologies(name, img_url, description) values ("Leo","/Horoscope/react-front-end/public/leo.jpeg","this is Leo description!!");
insert into astrologies(name, img_url, description) values ("Virgo","/Horoscope/react-front-end/public/virgo.jpeg","this is Virgo description!!");
insert into astrologies(name, img_url, description) values ("Libra","/Horoscope/react-front-end/public/libra.jpeg","this is description!!");
insert into astrologies(name, img_url, description) values ( "Scorpio","/Horoscope/react-front-end/public/scorpio.jpeg","this is Scorpio description!!");
